# Generated by Django 3.2 on 2022-01-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20220108_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlink',
            name='url',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
